//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACOUNT
    {
        public int ID { get; set; }
        public string EMAIL { get; set; }
        public string MAT_KHAU { get; set; }
        public string LINK_ANH { get; set; }
        public string HO_TEN { get; set; }
        public string PHONE { get; set; }
        public Nullable<System.DateTime> NGAY_DANG_KY { get; set; }
        public string DIA_CHI { get; set; }
        public Nullable<bool> TRANG_THAI { get; set; }
        public Nullable<bool> IS_REMOVE { get; set; }
    }
}
