//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanLoaiCV
    {
        public int ID { get; set; }
        public Nullable<int> ID_LOAI_CV { get; set; }
        public string GHI_CHU_LOAI { get; set; }
    }
}
